version: '3.8'

services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "uvicorn backend:app --host 0.0.0.0 --port 5000 --reload"

